name: Quality Assurance

on: [push, pull_request]

jobs:
  quality-assurance:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          tools: phpcs

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: |
          composer install

      - name: Check Code Quality (PHP Code Sniffer)
        run: |
          composer lint

      - name: Static Code Analysis (PHPStan)
        run: |
          composer lint

      - name: Unit Tests (PHPUnit)
        run: |
          composer test
